"""make_address_fields_optional

Revision ID: b17019176727
Revises: 20260820_01
Create Date: 2026-08-21 01:27:32.984142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'b17019176727'
down_revision: Union[str, Sequence[str], None] = '20260820_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'address_line_1',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('patients', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('patients', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('patients', 'preferred_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'English'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'preferred_language',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'English'::character varying"))
    op.alter_column('patients', 'zip_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('patients', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('patients', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('patients', 'address_line_1',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
